version: "3"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  app:
    container_name: app
    build: ./
    command: "python app.py --host 127.0.0.1"
    volumes:
      - .:/app
    ports:
      - 8000:5000
    depends_on:
      - db
    restart: always